import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "../styles/globals.css";

const workSans = Work_Sans({ 
  subsets: ['latin'],
  weight: ['300'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={workSans.className}>
      <body>{children}</body>
    </html>
  );
}
